GUNACCESSORIESFORSALE = 'GunAccessoriesForSale'
GEARTRADE = 'GearTrade'
GUNDEALS = 'gundeals'

SUBREDDITS = [GUNACCESSORIESFORSALE, GEARTRADE]

BLOCKED = 'BLOCKED'
FAIL = 'FAIL'
SUCCESS = 'SUCCESS'

STATUS = [BLOCKED, FAIL, SUCCESS]